# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

# Modifies text of upload button to show file name of selected file
# Also disables/enables submit button based on whether a file is selected
$ ->
  $('#submit-button').attr("disabled", true);
  $('#gram_picture').change ->
    if $(@).val() == ''
      $('#upload-button > span').text 'Select an Image to Upload'
      $('#upload-button').removeClass('file-added')
      $('#submit-button').attr("disabled", true);
    else
      $('#upload-button > span').text $(@).val().replace(/^.*[\\\/]/, '')
      $('#upload-button').addClass('file-added')
      $('#submit-button').removeAttr("disabled");
    return
  return

# ---
# generated by js2coffee 2.2.0
